apiVersion: v1
kind: ConfigMap
metadata:
  name: tesla-public-key
data:
  com.tesla.3p.public-key.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjm8vMTnS23F9Gh0JcsGBoHDu1CGA
    4t6XJxG3jncPRB0nKlmp4ucjkAXBD+yXQpByq19il4d041w/pS2XwdnrzQ==
    -----END PUBLIC KEY-----
