apiVersion: v1
kind: ConfigMap
metadata:
  name: tesla-public-key-nginx
data:
  default.conf: |
    server {
      listen 8080;
      location /.well-known/appspecific/ {
        root /usr/share/nginx/html;
        default_type application/x-pem-file;
      }
      location / {
        return 404;
      }
    }
