apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: teslamate
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  host: teslamate.aukia.com
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: oauth2-proxy-teslamate
    weight: 100
  port:
    targetPort: http
