apiVersion: v1
kind: Secret
metadata:
    name: teslamate
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:ptOmyuEpAqo7Kh9CNtbjjz6DPX2lTkRMzF8UQ7KQkN0UsiMsvMfXLCbOqbk=,iv:Y4XoOebHzf4D1VqpmpNufXienXW0H1o83kxNuR8/0IY=,tag:HxWwH5J6cAmXsJ7mtbnfpw==,type:str]
    tesla-client-id: ENC[AES256_GCM,data:qq0XjBRhq/4k4sRZR9E8/xhDDRGIUXPAYzDbm49jwjJqmQuW,iv:UZ7gTvi7Qi0qpXlvNl68Ftos6DFPBfdfePZLRdg9yq0=,tag:kNFJ2U6gPnluTdAxIW6XBg==,type:str]
    tesla-client-secret: ENC[AES256_GCM,data:uW/eD06+LkxCmTkxbVv4eFVg7n4p3CgzGGs=,iv:EHJdFgXJ1l5UBYW5DbLC6Z4GQ9SjHKsZi/ObBOMYg+0=,tag:SmQWxuySBOv35aAnAryCYg==,type:str]
sops:
    age:
        - recipient: age1v9p729ttu8u9pwe03a7ca0ym96t6h8u7mljyzfaa0jy284j2nspqmlt5mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWENCYi9wNU9tZ3pFeEFS
            aUhTYkNGYVI4Z204UzZDcm1sa2Y5SWgzWkFZCjlHZms3Qy9JMEZweFh5T25RQ3Ra
            RjArdXpwc09GZ2ZuZnkyazc1Z2llWFkKLS0tIGgvanY2OUdxNjNXVHV2TVk2MWYw
            SVpYTnlid0kyakliWEhveWQvdGNtZUUKGDGKC4JU0+xnlBBcWfhmbAACbI0aQSRs
            T5hWPyqPQK0o7h30py/OmOU/b3F69VEy0PtUqE+t59WPeTndZpDleQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T11:28:54Z"
    mac: ENC[AES256_GCM,data:uF/hf8uCupdhQMpSxNJ3xrDKA/eY7nMNC5EDEuwCuH1J6p/nIyau38KZeNWJ9sg1jAzeMrhm+d37aoLj/V3bt/R8KpQ6AbOgZJ67kmNjIedVQUhR3RU1nJ1FCEtQttkFL2Q845S5I0ojr21FSNi3y4ATuM8r5WjuIZCevo+zEDs=,iv:OAH7Vasl2BakINMm2ZBX6RMHeWozYTR2+1bN9m3R5IU=,tag:jML0/v1aDJWa1NRPE1+uug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
