#!/bin/bash
set -e

# Parse MARIADB_URL to extract components
# Format: mysql://user:pass@host:port/dbname
if [ -n "$MARIADB_URL" ]; then
  : "${MYSQL_HOST:=$(echo "$MARIADB_URL" | sed -E 's|.*@([^:]+):.*|\1|')}"
  : "${MYSQL_PORT:=$(echo "$MARIADB_URL" | sed -E 's|mysql://[^@]+@[^:]+:([0-9]+)/.*|\1|')}"
  : "${MYSQL_USER:=$(echo "$MARIADB_URL" | sed -E 's|.*://([^:]+):.*|\1|')}"
  : "${MYSQL_PASSWORD:=$(echo "$MARIADB_URL" | sed -E 's|.*://[^:]+:([^@]+)@.*|\1|')}"
  : "${MYSQL_DATABASE:=$(echo "$MARIADB_URL" | sed -E 's|.*/([^?]+).*|\1|')}"
fi

# Defaults
: "${MYSQL_HOST:=localhost}"
: "${MYSQL_PORT:=3306}"
: "${MYSQL_DATABASE:=emoncms}"
: "${MYSQL_USER:=emoncms}"
: "${MYSQL_PASSWORD:=emoncms}"
: "${REDIS_ENABLED:=false}"
: "${REDIS_HOST:=localhost}"
: "${REDIS_PORT:=6379}"
: "${EMONCMS_LOG_LEVEL:=2}"
: "${EMONCMS_DOMAIN:=false}"

# Generate settings.ini
cat > /var/www/html/settings.ini <<SETTINGS
; Generated by entrypoint.sh from environment variables

domain = ${EMONCMS_DOMAIN}

[sql]
server = "${MYSQL_HOST}"
database = "${MYSQL_DATABASE}"
username = "${MYSQL_USER}"
password = "${MYSQL_PASSWORD}"
port = ${MYSQL_PORT}
dbtest = true

[redis]
enabled = ${REDIS_ENABLED}
host = "${REDIS_HOST}"
port = ${REDIS_PORT}
prefix = "emoncms"

[mqtt]
enabled = false

[feed]
engines_hidden = [0,2,8,10]
redisbuffer[enabled] = false
phpfina[datadir] = '/var/opt/emoncms/phpfina/'
phptimeseries[datadir] = '/var/opt/emoncms/phptimeseries/'

[interface]
feedviewpath = "graph/"

[log]
level = ${EMONCMS_LOG_LEVEL}
SETTINGS

echo "emoncms: settings.ini generated, starting..."

exec "$@"
