apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1f58Z2SsjNeI5WU1zBkDlbnb4E7WvI+pcGW4gx4T2YUtewPE4JVHpUIC/YX98g==,iv:Hap6C4Bk/YZG8BaRDEijkR9RAA6JJ5TafqqiZL5I1To=,tag:XsDp0Xai4UWyNy0yXnQNHg==,type:str]
sops:
    age:
        - recipient: age1v9p729ttu8u9pwe03a7ca0ym96t6h8u7mljyzfaa0jy284j2nspqmlt5mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMnJqZWVOQVVtQmNmT2p2
            R3M2ejF3QlNYU1NNNmkyRWZvRzhMNjJZcGpRCjRkWmhBeitYRXJGRkhHL1czWTRw
            aFJpdUZMcEpzSVdEZ2I1YXh5QWk3Uk0KLS0tIGp0bFQ5ZFluWHRUZkkxdUc2alBk
            aWJoaDFoWVljdmdNcUZvbklzZjdtZmcK6ZZxYcgFsStsggAjpBpXu0vQggNQ3zuH
            jQNu+iSrkBWFV/eEd3JBpwg/oAOpBZ/fHs7cWAvVtIewNn8OYsexZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T08:55:47Z"
    mac: ENC[AES256_GCM,data:8sXsiTq4sXh8iUxvIEcoNEaG76O9/bhRGEO9APbGaOivpECncjbtp/ZSY90TJEdoQjO1ctpSoK1dF1OdgsIb7HKRfu0HX5wccBxoz72H4LKP7t1lohV/NOc6AkDQzgl2Hi5GO7IbKAw2QRpw+dtPaBk0NwCcgiKkkp88iu9Mm3c=,iv:zNMC5Ianjoy817kg2Nda6bvSCXhcCKZp7AlAAAh666I=,tag:IvTZ6Hl5+lYtFgVuzXOPCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
