apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
  labels:
    app: evcc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: evcc
  template:
    metadata:
      labels:
        app: evcc
    spec:
      containers:
        - name: evcc
          image: dockerhub.vshn.net/evcc/evcc:latest
          env:
            - name: HOME
              value: /home/evcc
          ports:
            - containerPort: 7070
              name: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: 7070
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /home/evcc/.evcc
            - name: config
              mountPath: /etc/evcc.yaml
              subPath: evcc.yaml
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: evcc-data
        - name: config
          secret:
            secretName: evcc
