apiVersion: v1
kind: Secret
metadata:
    name: evcc
type: Opaque
stringData:
    evcc.yaml: ENC[AES256_GCM,data:x0aXL8eC1Pn6mo5WnSoioMJepPAgDxB28bqlZ9cmI87DMqn2lJmn/ehI4SEXzRO3fWQ0WTUb2UXL1KWftwSEt06g07g70Z9Dll1YKqhMZcHYWb6tJ6Ez/S9B+gYTUlZmdWlXMyOGGJnvjKOxi3vTFd5Hjwwbot0jzRIC2Mmg8dcZgZ5Jdgcfczq2F/Z+/3GyOrMc1Yc4o7I4HzxMhTjJA335fUOhfhUmyIbCR3SY7l5YjrukJFk9jVZt/hE4nBJvfEWEDZTzs004XCq7l+PfSobjhZR4SYKMkzR+rFVzDOcFStCW7FqXsvQzaGytkDV6C47rU/afraeoQDigHj0sJkfH1/gCAMHpRAn799lj8kh+HGPC6ugTxKjGLVmTdLRHgPlhD37dBRgbmv+LdcI9OSSQE862Xba/knaP74dJi96YKZDnHg8zXpv7x0CYwHb9x34jkZ5l9iVOkUzQXhsCo3lRlodOEFjkDzlZw9FdVI98wjl+dEKZr9p1xVChve2Gr44jI4DnFQ+oknsHCHwI5BlK6o/kOCT4qJhKX/Qm+btVU9110LSoH2KCytcdBEo1TBFxTTME5ryUc1RCxUjRg93GfuMpA89sWzSPvTkqxZTe14oRX6doAHwCVaGQShzRsNDyaqcj3uJR/PvcEWpQ2W6axy4j5vx7xrFePu/g5rQ2ALC36YggQeX01sG5CqELPY9ce73Z0H1vQwGFLxTDTE2fsngg2ekgGNnTv6H99diFJC+yAL0UrLS/PqkTno+jGzIWo3ROvzFxG/C3saQQuONhg9njKWUjk8HpKiNKUk6rKmxd5I10odlAwll93kjsHXXlmoghZ1Hg/FujOl7dwYW3OyuZ4L315vre9p4PCT5A4XK5/7Je0iqkpTu96Z4tMz83yXc=,iv:oq61E/19tpksBaPTF2zAD44krdSEW4FLT/ixIM+3oGo=,tag:9qTJBoqkE6Or7YN08HS0KQ==,type:str]
sops:
    age:
        - recipient: age1v9p729ttu8u9pwe03a7ca0ym96t6h8u7mljyzfaa0jy284j2nspqmlt5mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUHNCeFJyS0Y0UVJreUFT
            aS9jdlJ0b2J0cll4MlE3cjcyNnlEU2NFZjFVCjdxK1dpVnVQTnpNZXFUL1QzSkl0
            bGFCcHZvdHdtUnc0QXc2ZzFVRjRncTQKLS0tIEtDdERURE13UThJVnIrTWdNQ1NI
            MmtkUnZrSUVDSkxqVGJJN2o2aUlJZlUKpxQEhr3DuzaN9aJKoJ2PcAGg3mGDIGGa
            xsMMm1OQKCspZtKt2OQaWoU86LYdsBjJES4UYbS+NaZIJVIU/zC6kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T17:03:08Z"
    mac: ENC[AES256_GCM,data:AF110Jgl+YhEdqKhfMtY/nWKBU3fms4lsROQXfZdvciiCY361/DFOgR/Vr+xdg0IN6I8f4/cwVFdI1i5w/tHG4mSquv4aD8QtRsCRpbeIHWeH/5BlXMDFBHkEetZfwf6HBibqD+amEPmiY6iBleiAw9ABXx8zglsji/5T9C3viM=,iv:SJSxztb1hCprWi0lzunIi25qJB1++JSgVcD+igafEr0=,tag:0uplLAYA+lF4hfEcKyxntQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
