apiVersion: v1
kind: Secret
metadata:
    name: evcc
type: Opaque
stringData:
    evcc.yaml: ENC[AES256_GCM,data:4aIjMWETXg/R0Y1NM0WkVvbD+3+Dr37nNt+Kumf+wKDf1a07rcycSqr5M3vSYR/Vj2pA16GNHLQZoygLp0DNLq3XFwZEGq0ov6JhV6BDzW5BSlrX3y1P7G2sDOhJkqDI+PhnYbTBIIo5SeJTmA2+pAh/+TfHU39w3jY5owplpjvUxCibA7iEoVxmlCM5vHHbS5c+ee5XSBraI4uK2cg1Frxk0yektTHFmgu6S9/xBgEtnATBQl/Mrlka7jz04wVAEcJk94ewyRxclzrHmAphjjnvAZpwSLHpZaPKwDnSqcUEatGH75kXte5Vs+ZXKD14JMzrgeWUDM5zCZ3wKCKyzxHIkaac/chXUaiJIg/91qWzLF8TTW/49IC1BVfe8XnzBX47/sD7KY3AmBY6SseU9ehHOvuh6YVTeDDE+vtChJq6P7JHko6X0xss4ZU0VVC304+Wco0Xp1QFUEIpDdfWr4LKv6/cAirGnflPIkWE6ayFkKDWobrmOcL79YIl7/XXP9Zwh5ppaFAQv6e/FjYVgBYG5RbR+limINYm5vf96CJgYFdMGgRfZzqQ0XTbsRqRmB3XCpOc669XEAj3EK2gzl5sra2KUCOyxIybXC3NVN8bkOzRs8KoFkACBVUuZOabDqt/S8dz4gi99sqRLSE/yogfW/mrfkcG0WVd7SP/FtmImjaxA9Lqvm7+0LeeigGkEUNK/3EbuIDL5VyJpsUZchHRm6NXAz/NHK84lIqagMFoWGvW4jdSnH5hFlLsXzvDiW0N0/aXLyYM2Z+OPJn/xAmcUoGpiVooEfGqC4AFs3Yi94/AlzETW8D0GVTc/Mi87UeAM33Mc7YXkidHVg0rMgoBGQ0JvShkJ4gUyEzBk/1wkZpKYJfq1W6iAP2bVA8Rr+pkd8wav/d2TQjNnkpSK7+nd0RXDgSj1H1nPRnneXEZ+TA7qcPjd4M9i7dQDeFE1YxjPEkhGs6XDSQN4Wng,iv:eLJ9wxEUIema6wLt/63inDJM8w3IbfIPKKcqsMoqp8g=,tag:5yDmH8sbdtKuav11a9Wcdg==,type:str]
sops:
    age:
        - recipient: age1v9p729ttu8u9pwe03a7ca0ym96t6h8u7mljyzfaa0jy284j2nspqmlt5mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UkJxVEQxa1dFYlVjWUV5
            K0U4S3dHalo2QldXcDVwNWxrYXYrdXV2YzNBCkZoSlpaYVQ2dEJpZ3BYeGJJT0VP
            dkpET1oxWVp3TURnbTVFaE5WRVMzTDAKLS0tIDdKZmRhcVFWcUhmR202UitlWFUv
            ZTVOZjhHMkFxRWtpekU2ci84dVJNK0UKKDAM2wNBDjvbCyA5bXMMppifYtFdkx4E
            3a/hWMAo7+oF9HpI0+UdlWV2Zrk4w5EK2SDThaHxlrqekIEC/ZAiCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T06:41:46Z"
    mac: ENC[AES256_GCM,data:8dcYiMHmI08MzYXN+TGngbyaG0NONBqr5uWzS4nYgcxESNYMkyuxJpCYKiAEwfuFv8kORzM84QxPDSuVcFgvk+TU38ChpLmEMZGMadbjQx3tBiZ4OGxlgJNaZXLIVBHwWNP7zfj7cAF7gpSYAF0L4VXK6T7I8w4/NuOzWXgNPOQ=,iv:qaYQdSRmAxdeySO/D9PgXUyrjO43JZyveiApNtaI3ts=,tag:9D9Wo9Fkl8ngQDs36Zh6Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
